### ISSUE TITLE
Add link to github repo of Applications

### ISSUE THREAD

**Issue by meghajain-1711** [mozilla/glean-dictionary#101]
As per the Glean dictionary proposal : 
![image](https://user-images.githubusercontent.com/59704142/95766930-a02e0200-0cd1-11eb-9841-4c71b1c2de03.png)

Application page should have a link to the application's source repository which is currently missing. 

Where to add: 
1) Below the Header for application name / Make the Application Name a hyperlink to the source repo
![image](https://user-images.githubusercontent.com/59704142/95767066-cd7ab000-0cd1-11eb-9222-505fe7ea1053.png)

How to add:
We might need a pre-existing database with this information 
OR
have to store it in a JSON format , which would need maintenance if any application is added.

Code to change : src/pages/AppDetail.svelte

**Comment by meghajain-1711** [comment]
Hi @wlach what do you think about this ? 

Do we have any predefined database for github repo of the applications ?
Can I add it to the page ?

**Comment by DawoodShahat** [comment]
Hey, @meghajain-1711 Here is a link to all the repositories

[https://probeinfo.telemetry.mozilla.org/glean/repositories](https://probeinfo.telemetry.mozilla.org/glean/repositories)

If you look at public/build/data/apps.json in the repo
you will find each app with the associated URL.

Hope this helps.

**Comment by DawoodShahat** [comment]
If you want to make the apps linkable to its source repo. You would probably want to change
[https://github.com/mozilla/glean-dictionary/blob/main/src/pages/AppList.svelte](https://github.com/mozilla/glean-dictionary/blob/main/src/pages/AppList.svelte)

**Comment by meghajain-1711** [comment]
@DawoodShahat AppList would be the first page , the apps there would link to their own AppDetail page. 

Hence I figured [as mentioned in the issue] that the update should be in the AppDetail.svelte

**Comment by DawoodShahat** [comment]
Yes, they would link to their own AppDetail page but you can add a link beside each app that takes you to an external page(source repo).

**Comment by wlach** [comment]
Hi @meghajain-1711 @DawoodShahat -- this was actually addressed by #112 -- feel free to look there for the solution.

**Comment by meghajain-1711** [comment]
Haha , it seems the data is in index.json as app.url  !!
And someone has recently added it as well !

**Comment by meghajain-1711** [comment]
> Hi @meghajain-1711 @DawoodShahat -- this was actually addressed by #112 -- feel free to look there for the solution.

Yeah ! Just saw ! 20 secs too late , my bad !
