### ISSUE TITLE
Processing invalid links in Bugs and Data Reviews Json 

### ISSUE THREAD

**Issue by meghajain-1711** [mozilla/glean-dictionary#102]
**Issue description**
glean.page.path bugs and data reviews hyperlinks takes to invalid Bugzilla page. 

**Steps to reproduce the issue :** 
http://localhost:5000/data/glean-js/metrics/glean.page.path.json , check the json key: value pair of bugs and data_reviews
"bugs": ["https://bugzilla.mozilla.org/show_bug.cgi?id=actually-we-dont-have-this"], "data_reviews": ["https://bugzilla.mozilla.org/show_bug.cgi?id=actually-we-dont-have-this"],

**What can be done here :** 
1. Check with the data source for wrong data reason and process it.
OR
2. Preprocess such noisy data at UI end. 

Solving this issue might also require spec'ing what would the UI page say when such bugs/links are found.

**Comment by meghajain-1711** [comment]
As @acmiyaguchi confirmed, this noisy data was due to glean-js being an experimental prototype app, so it didn't actually have a bug and data-review. Thanks @acmiyaguchi :) 

@wlach is there some data pre-processing which we need to manage under glean dictionary proposal for similar noisy data later ? For eg: bugs and data review links which might be invalid.

**Comment by wlach** [comment]
My sense is that it's probably not glean-dictionary's job to validate this kind of bad data. That should be taken care of via tools like [glean-parser](https://github.com/mozilla/glean_parser/) -- if the data we ingest has a bad link in it, hopefully people will notice and we can fix it at the source. 😄
