### ISSUE TITLE
Persist search state in BigQuery table view

### ISSUE THREAD

**Issue by wlach** [mozilla/glean-dictionary#106]
In the BigQuery table view we currently allow the user to search through the column names to find the ones of interest:

![image](https://user-images.githubusercontent.com/20569/95868613-680dda00-0d38-11eb-89c0-d27b9c3a3ee9.png)
http://localhost:5000/#!/apps/mozphab/tables/usage

It would be very handy if we could *persist* that search in the URL (and restore it when they visit it), so that people could link to specific views and have the search prepopulated. In the above example, that would be:

http://localhost:5000/#!/apps/mozphab/tables/usage?search=build

To perform this task, have a look at the documentation for page.js, which is what we currently use for routing: https://visionmedia.github.io/page.js/

You will probably need to modify the main router (`App.svelte`) in addition to the component for the table view.

**Comment by wlach** [comment]
After talking to @oalbacha, I'm going to reassign to @Riju19

**Comment by Riju19** [comment]
Pull Request #170 fixes this issue. Can we close this one?

**Comment by wlach** [comment]
> Pull Request #170 fixes this issue. Can we close this one?

Yup! Usually it closes automatically, will do so now.
