### ISSUE TITLE
Better handle cases where application/pings/metrics/table do not exist

### ISSUE THREAD

**Issue by wlach** [mozilla/glean-dictionary#108]
Currently we just silently fail if the user navigates to an entity that does not exist. e.g.: 

http://localhost:5000/#!/apps/burnham2
http://localhost:5000/#!/apps/fenix-nightly/pings/activation-doesnotexist

It would be better if we displayed some kind of friendly error page saying something like "Could not find application `burnham2`" or "Could not find ping `application-doesnotexist`". I don't expect this to happen frequently but this sort of thing can happen occasionally (e.g. if an application is added and then withdrawn)

To accomplish this task, you'll want to create a new Svelte component to cover this functionality and update each page to use/display it in the event that fetching information fails.

**Comment by nonbinaryfrog** [comment]
Sure! I'll do my best!
