### ISSUE TITLE
We should gather all metric/ping types, not just those specified by the applications

### ISSUE THREAD

**Issue by wlach** [mozilla/glean-dictionary#109]
*This issue is intended as an onboarding task for potential outreachy applicants. Please do not work on it unless you have completed the initial qualification task and it has been assigned to you.*

Currently we're only gathering metrics and ping data from the applications themselves, not those specified by the libraries (e.g. the `events` ping is part of glean-core: https://github.com/mozilla/glean/blob/2261845761251d91b6968f29846dc3aabbc0cc45/glean-core/pings.yaml#L80)

Mozilla Schema Generator (which does something similar to what we do) enumerates dependencies for each application and gathers data for them e.g. https://github.com/mozilla/mozilla-schema-generator/blob/1264148ff82adc3357de33a25541f1313f93449f/mozilla_schema_generator/glean_ping.py#L126

We should modify our `build-glean-metadata.py` script (https://github.com/mozilla/glean-dictionary/blob/main/scripts/build-glean-metadata.py) with similar logic.

**Comment by mhmohona** [comment]
Can I work on this issue @wlach?

**Comment by wlach** [comment]
So on reflection, I think this issue is quite a bit harder than I initially thought, and I think the rest is better done by me since there's a fair amount of subtle Mozilla-specific context required for a proper solution. Thanks @mhmohona for a great start!

**Comment by mhmohona** [comment]
It's my pleasure to learn from you.
