### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by edward-hong** [mozilla/glean-dictionary#113]
Currently there's only an example test. It would be a good idea to add some testing maybe with something like svelte-testing-library along with Jest. This way we can familiarise ourselves with the codebase through writing some tests.

**Comment by wlach** [comment]
Hi @edward-hong, this is a good idea though the application doesn't have a lot of business logic at the moment so there's not a ton to test. I think running storybook snapshot tests might be a better approach at this point, see mozilla/glean-dictionary#117

Let's keep this open though and return to it later. I'm sure we'll start accumulating stuff to test before too long...

**Comment by wlach** [comment]
We now have one test:

https://github.com/mozilla/glean-dictionary/blob/main/tests/state.urls.test.js

I'm sure we'll add more as time goes on. Closing this one.
