### ISSUE TITLE
Page breaks when navigating to the ping information

### ISSUE THREAD

**Issue by acmiyaguchi** [mozilla/glean-dictionary#114]
Navigating to a page for ping information (e.g http://localhost:5000/#!/apps/mozregression/pings/usage) leads to a broken page with the following error.

```
Uncaught (in promise) Error: {#each} only iterates over array-like objects.
    validate_each_argument index.mjs:1615
    create_then_block bundle.js:2938
    update index.mjs:1032
    handle_promise index.mjs:1065
```

**Comment by DawoodShahat** [comment]
Hey, I tried to reproduce the error, and It works fine on my end.

![Screenshot 2020-10-14 at 2 53 19 AM](https://user-images.githubusercontent.com/19612755/95920210-6e4b9700-0dc8-11eb-9962-713c3197c78d.png)

**Comment by acmiyaguchi** [comment]
Thanks! Based on your comment I figured out that the data format changed and reran `build-glean-metadata.py`, which fixed the issue.

**Comment by meghajain-1711** [comment]
hey @acmiyaguchi ! The link works fine for me too, both on Chrome and Firefox  :)
