### ISSUE TITLE
Have the UI flag when an app is on the prototype stage

### ISSUE THREAD

**Issue by brizental** [mozilla/glean-dictionary#116]
On https://github.com/mozilla/probe-scraper/issues/244 we added a flag that signals when an app is still on the prototype stage. 

We should have the dictionary show that on the UI somehow. 

This bug should be handled in two stages:
1. Define how we are going to add this flag to the Glean dictionary's UI, discuss the proposed solution (can be done on this issue's comments);
2. Implement whatever is decided.

**Comment by singhvaishnavi** [comment]
An app can be flagged on the UI which is on the prototype stage by:

1. Adding an asterisk on the end of the app name which will be only rendered if the value of `app.prototype` is `true`, for eg: `glean-js*`

2. Adding a label (color red) after the list of apps which shows _* Application under developement_

**Comment by brizental** [comment]
Hey @singhvaishnavi thanks for the proposal! On 1., do you mean to add such asterisk on the dropdown list? Like so:

<img width="410" alt="Screenshot 2020-10-15 at 10 07 49" src="https://user-images.githubusercontent.com/25176023/96095008-53634a80-0ece-11eb-924d-2c17bb7912be.png">

Personally I don't think it is necessary to add it in the dropdown, this could be a banner on the app's page. This way, when the user reaches the prototype app's dictionary page they are immediatelly warned that they are looking at a prototype app. Something sort of like this (haven't thought too much here about the text or layout, just a draft):

<img width="1391" alt="Screenshot 2020-10-15 at 10 21 27" src="https://user-images.githubusercontent.com/25176023/96096713-6bd46480-0ed0-11eb-9f81-9ee8fd799923.png">

@wlach Since this would require UI changes, would you mind taking a look and telling us what you think about the proposed solutions?

**Comment by brizental** [comment]
Now that I think about it, a more drastic solution would be to just not list prototype apps at all on the Glean Dictionary, I started wondering now if there is any value to showing them at all. That would mean doing to prototypes the same thing we are doing to deprecated apps (see https://github.com/mozilla/glean-dictionary/issues/53).

**Comment by wlach** [comment]
Hi @brizental @singhvaishnavi -- the first screenshot @brizental posted is not applicable (that was an older version of the Glean/Probe dictionary which focused more on metrics). 

However! I think the second screenshot (with its warning text) is exactly what we'd want on the app page (http://localhost:5000/#!/apps/glean-js). On the index page (http://localhost:5000/), you can flag applications that are prototypes using the same technique @JoyLubega used in #112 (putting a "pill" next to the application)

Does that help?

**Comment by brizental** [comment]
> the first screenshot @brizental posted is not applicable (that was an older version of the Glean/Probe dictionary which focused more on metrics).

Oops, I didn't realize we had a new UI.

> However! I think the second screenshot (with its warning text) is exactly what we'd want on the app page (http://localhost:5000/#!/apps/glean-js). On the index page (http://localhost:5000/), you can flag applications that are prototypes using the same technique @JoyLubega used in #112 (putting a "pill" next to the application)
> Does that help?

Definitely, this makes a lot of sense.

@singhvaishnavi Do you think you can go ahead with the implementation after this discussion?

**Comment by singhvaishnavi** [comment]
Yes, I can implement adding the pill next to the prototype apps, similar to #112
