### ISSUE TITLE
Run storybook tests in ci

### ISSUE THREAD

**Issue by wlach** [mozilla/glean-dictionary#117]
Storybook snapshot tests in CI (where we verify that stories still render after a pull request) can often catch problems, e.g. it was helpful in the iodide project (see iodide-project/iodide#2506). I'm not sure how to set this up in Svelte but I'm guessing it should be possible. You can see the aforementioned PR for iodide for some ideas.

**Comment by wlach** [comment]
@edward-hong care to give this a try?

**Comment by edward-hong** [comment]
Yea sure I'll take a crack at this

**Comment by DawoodShahat** [comment]
@wlach Can I work on this issue?

**Comment by wlach** [comment]
> @wlach Can I work on this issue?

I think so, it's been nearly a month so am guessing Edward has moved on. This would be hugely valuable BTW (it would give us enough confidence to auto-merge dependabot PRs, which is currently a manual process)

**Comment by DawoodShahat** [comment]
Yeah thanks, will start working on it right away.
