### ISSUE TITLE
"(Glean.core.Config) A list of tags cannot contain more than 5 elements or less than one." error in production

### ISSUE THREAD

**Issue by brizental** [mozilla/glean-dictionary#1188]
It seems we are entering this conditional https://github.com/mozilla/glean-dictionary/blob/2246643fb0b8bc936252c1e6ea4d9967020884cb/src/telemetry/index.js#L54-L56 in production. Which we should not be.

@Iinh What is the value of the GLEAN_SOURCE_TAGS environment variable in Netlify production? It should be `undefined`.

**Comment by Iinh** [comment]
@brizental I just checked, we didn't have `GLEAN_SOURCE_TAGS` in the list of the environment variables. Adding now; does the below look correct to you?

<img width="881" alt="Screen Shot 2022-03-21 at 9 24 34 AM" src="https://user-images.githubusercontent.com/28797553/159270112-c2d88fd3-0e52-4744-9374-e38a4fd51e21.png">

**Comment by brizental** [comment]
> @brizental I just checked, we didn't have GLEAN_SOURCE_TAGS in the list of the environment variables. Adding now; does the below look correct to you?

Thanks for checking @linh, hm. `GLEAN_SOURCE_TAGS` is the correct, that is what I meant by "it should be `undefined`.

This is a mystery then, why are we going inside that conditional in production then? 🤔 

I'll investigate this tomorrow.
