### ISSUE TITLE
Add a backlink to the application which produced the ping

### ISSUE THREAD

**Issue by mhmohona** [mozilla/glean-dictionary#127]
According to the proposal, on ping page there should a backlink to the application be added which produced the ping. 

![proposal](https://user-images.githubusercontent.com/14244685/96362188-66378280-114d-11eb-8cd2-92f436a9ca25.png)

Where to change: https://github.com/mozilla/glean-dictionary/blob/main/src/pages/PingDetail.svelte

**Comment by wlach** [comment]
This duplicates #83.
