### ISSUE TITLE
External link should be opened in new tab

### ISSUE THREAD

**Issue by mhmohona** [mozilla/glean-dictionary#142]
Opening an `external link` in a new tab allows one to explore the other site as much as they want without having to hit the back button again. It helps to keep focus in one place without losing other websites' information. 

Currently, **metrics page** opens external links in new tab. **Pings page** and **Tables page** need to be updated. 

Here another thing to be noted, we should not open `internal link` in the new tab because it might confuse users. Also, Glean dictionary has the flexibility to navigate back or elsewhere according to users' needs. So for this, keeping users in the same tab helps them understand the navigation flow better.

**Comment by wlach** [comment]
Not sure about this one, it's fairly easy to open links in a new tab by right clicking on things and people might prefer it that way. We should get more feedback from the intended audience of the tool (data practitioners at Mozilla) before going ahead with this. I'm going to leave this open for now, but close the pull request.

**Comment by mhmohona** [comment]
So when I was checking the ping page and matrics page for the first time, for matrics page external links were opening in new tab but for ping page it was not. I got confused at first why same thing is happening in two different ways for two pages. I thought maybe it would be better to make thingswork in same way for all pages. Thats why rised this issue and made PR.

**Comment by wlach** [comment]
Incidentally we can set navigation links to open in a new tab by default via the `<base>` element. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base

**Comment by mhmohona** [comment]
> Incidentally we can set navigation links to open in a new tab by default via the `<base>` element. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base

@wlach, shall I refactor #143?

**Comment by wlach** [comment]
> > Incidentally we can set navigation links to open in a new tab by default via the `<base>` element. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base
> 
> @wlach, shall I refactor #143?

Sorry for the late response on this. I think still no, for now: I'd like to get more feedback from the potential users of this thing first.

**Comment by mhmohona** [comment]
Alright!
