### ISSUE TITLE
Improve filter 

### ISSUE THREAD

**Issue by mhmohona** [mozilla/glean-dictionary#146]
In the filter box when we search for something and it doesnt match with any item, just a blank page stares at us. There should a text telling search doesnt match with any application or martics.

**Comment by LilyLME** [comment]
@mhmohona I would like to work on this.

**Comment by LilyLME** [comment]
## Preview

![Screenshot from 2020-10-20 15-26-59](https://user-images.githubusercontent.com/38939048/96600431-d595a980-12e8-11eb-8044-e655a1a735e4.png)

**Comment by mhmohona** [comment]
Thank you for your interest but have already added fix for this issue @LilyLME 😄
