### ISSUE TITLE
Enable filtering by Glean metric type

### ISSUE THREAD

**Issue by Dexterp37** [mozilla/glean-dictionary#1462]
When I use the Glean dictionary and I don't have a specific name for a metric, I find myself wanting to restrict skimming through the metrics only to specific types, e.g. events.

It would be useful to have some way to expose such a functionality. 

"As a user, I want to be able to only see metrics of a given type (e.g. events) to search more effectively if I don't know specifically what I'm looking for"

**Comment by Iinh** [comment]
Thanks for the request @Dexterp37! The implementation for this feature should be pretty straightforward since we already have full-text search available. I'll start working on it.
