### ISSUE TITLE
Enable filtering by expiry date

### ISSUE THREAD

**Issue by dnarcese** [mozilla/glean-dictionary#1467]
I would love a way to filter by expiry date and to be able to choose a range.

Every 6 months I do an audit of our telemetry and renew metrics that are expiring soon. Currently I have to search through the metrics.yml.

It would be great to have a filter on the glean dictionary to see, for example, all metrics expiring in the next 3 months, or next 6 months, etc.

**Comment by Iinh** [comment]
Hi @dnarcese, thanks for filing! I'm going to prioritize this work in the next few weeks as I've noticed recently more users are asking for features that help signal metric expiry information.
