### ISSUE TITLE
Report the 'union' tables for products that have them

### ISSUE THREAD

**Issue by Dexterp37** [mozilla/glean-dictionary#1479]
Some products (e.g. [Focus Android](https://github.com/mozilla/probe-scraper/blob/926f0af1fa2a5e145fc0d7221905f72bba549279/repositories.yaml#L670-L685)) have multiple channels, with one app id per channel (that's the case mostly for mobile products). These products generally have a dataset that essentially UNIONs the data of all the channels.

For example, Focus Android has the `focus_android`  dataset that is the union of `org_mozilla_focus`, `org_mozilla_focus_beta` and `org_mozilla_focus_nightly`. The availability of such a UNION'd dataset is reported by the probe-scraper. It would be nice to mention that where we link to the tables.

**Comment by Dexterp37** [comment]
cc @scholtzan

**Comment by scholtzan** [comment]
These tables are generated through the `glean_usage` generator: https://github.com/mozilla/bigquery-etl/tree/main/sql_generators/glean_usage
