### ISSUE TITLE
Support version-based as well as date expiry

### ISSUE THREAD

**Issue by edugfilho** [mozilla/glean-dictionary#1497]
Currently [expiry version numbers are supported for `Firefox Desktop` but other apps are assumed to have `expiry` as a date. ](https://github.com/mozilla/glean-dictionary/blob/cbda56f858db72b0cfce4eaa493843a459c4ffc6/etl/expiry.py#L13) However the current state is that `expiry` can be one or another:

>by @chutten: 
 _`expiry` is a version in many (perhaps even most) cases, but can also be a date (and these can be mixed within the same project)_

Lack of such support results in the `expiry` field being `null` for certain metrics such as `tracking_protection.tcp_cfr_shown`, and because GLAM defaults to `expire: never` in the absence of the field, we end up with inconsistencies between [GLAM](https://glam.telemetry.mozilla.org/fenix/probe/tracking_protection_tcp_cfr_shown/explore?aggType=avg&currentPage=1&ping_type=*) and the [metric's definition ](https://github.com/mozilla-mobile/fenix/blob/ac64ec9efffcf15ff0019a59f8e6a7b18fab5f70/app/metrics.yaml#L4862-L4877)

**Comment by badboy** [comment]
I'd like to help here to get that fixed.

**Comment by edugfilho** [comment]
Reopening due to https://github.com/mozilla/glean-dictionary/pull/1499#issuecomment-1307603864
