### ISSUE TITLE
Render markdown in description fields

### ISSUE THREAD

**Issue by wlach** [mozilla/glean-dictionary#153]
Currently we're now rendering markdown in Glean description fields, which doesn't look great:

![image](https://user-images.githubusercontent.com/20569/96788307-490aea00-13c1-11eb-870f-fb26f8b2e4db.png)
http://localhost:5000/#!/apps/mozregression

We should render these types of fields with markdown. For the [schema dictionary](https://github.com/mozilla/schema-dictionary) I used the `marked` parser, which seems to work pretty well: https://www.npmjs.com/package/marked

It seems most likely that we'll define a svelte component for rendering this type of information, in which case we should add a story for it in: https://github.com/mozilla/glean-dictionary/tree/main/stories

**Comment by alvesitalo** [comment]
I sent a pr https://github.com/mozilla/glean-dictionary/pull/155 fixing this @wlach.

**Comment by wlach** [comment]
> I sent a pr #155 fixing this @wlach.

Thanks! I will have a look at it on Monday.
