### ISSUE TITLE
Getting a 404 on console for favicon.

### ISSUE THREAD

**Issue by LilyLME** [mozilla/glean-dictionary#154]
```
GEThttp://localhost:5000/favicon.png
[HTTP/1.1 404 Not Found 0ms]
```

**Comment by wlach** [comment]
I believe this is web browser default behaviour to just check for this, so we're not seeing this because of anything we're doing wrong. That said, we should create/add a favicon for sure at some point for sure.

**Comment by LilyLME** [comment]
Great, whenever that's (favicon) available, I would just go ahead and add it then.

**Comment by acmiyaguchi** [comment]
It's actually missing from the project (as opposed to being browser behavior).

https://github.com/mozilla/glean-dictionary/blob/df3b4005f151b82d9faa0f0751658ec31dc85aa3/public/index.html#L9

**Comment by LilyLME** [comment]
## OPTION ONE

![imageedit_2_7301618571](https://user-images.githubusercontent.com/38939048/99186487-e5ba7080-2750-11eb-9d10-7dd4de46cb1b.png)

## OPTION TWO 
![imageedit_3_2666423012](https://user-images.githubusercontent.com/38939048/99186490-e7843400-2750-11eb-8aef-04a24de71537.png)

## OPTION THREE
![imageedit_3_8161345328](https://user-images.githubusercontent.com/38939048/99186493-e81cca80-2750-11eb-9696-274ad5780d4a.png)


@wlach What do you think here?

**Comment by LilyLME** [comment]
The rough views can be cleared, so each template is just to give an idea.

**Comment by LilyLME** [comment]
The rough edges would be cleared, so each template is just to give an idea.

**Comment by wlach** [comment]
@LilyLME Sorry for the late reply on this. I think ideally we would have unique branding for the Glean dictionary but I think this is definitely better than nothing. Option (2) looks good to me, it probably will look reasonable when scaled down. @Dexterp37 @mdboom  does this seem like reasonable use of the glean assets to you?

**Comment by Dexterp37** [comment]
> 
> 
> @LilyLME Sorry for the late reply on this. I think ideally we would have unique branding for the Glean dictionary but I think this is definitely better than nothing. Option (2) looks good to me, it probably will look reasonable when scaled down. @Dexterp37 @mdboom does this seem like reasonable use of the glean assets to you?

@wlach yes, Option (2) looks good to me too! FWIW:

- [This](https://glean-dictionary.netlify.app/favicon.png) is the favicon from the currently deployed https://glean-dictionary.netlify.app/ .
- If that's not good enough, we also have vector-based Glean assets to derive the favicon from.

**Comment by wlach** [comment]
Oh right, I didn't even think about looking at the early glean dictionary! Moving ahead with option (2) by just copying what's in https://glean-dictionary.netlify.app/ seems like the best option -- I believe it's stored here: https://github.com/mozilla/probe-dictionary/tree/sveltify/public . Thanks @LilyLME for exploring the solution space -- I think this issue is now open if someone wants to look at it.
