### ISSUE TITLE
Looker links in Glean Dictionary are broken

### ISSUE THREAD

**Issue by rebecca-burwei** [mozilla/glean-dictionary#1619]
For example, on this page in the Glean dictionary: https://dictionary.telemetry.mozilla.org/apps/firefox_desktop/metrics/urlbar_pref_max_results

![image](https://user-images.githubusercontent.com/13172162/223768229-2693671c-8024-4c28-ba9f-719b4f888885.png)

the links boxed in red are broken

**Comment by rebecca-burwei** [comment]
@Iinh can you help triage this ticket?

**Comment by Iinh** [comment]
> @Iinh can you help triage this ticket?

I'm looking into it. Thanks for reporting!
