### ISSUE TITLE
uBlock Origin blocks parts of the Glean Dictionary website

### ISSUE THREAD

**Issue by travis79** [mozilla/glean-dictionary#1682]
The text of "ad_impression" seems to trigger uBlock to prevent the following page from loading. https://dictionary.telemetry.mozilla.org/apps/firefox_desktop/metrics/serp_ad_impression

**Comment by jamesteow** [comment]
It's because UO uses EasyPrivacy in their Privacy filter lists: https://github.com/easylist/easylist/blob/f69947c58e201d9797375f8eba5b790527730b99/easyprivacy/easyprivacy_general.txt#L5421

**Comment by wlach** [comment]
Similar issue: #550
