### ISSUE TITLE
Descriptions of metrics on app page seem incorrect

### ISSUE THREAD

**Issue by wlach** [mozilla/glean-dictionary#190]
For example on https://glean-dictionary-dev.netlify.app/#!/apps/fenix we see this on the second page:

<img width="907" alt="image" src="https://user-images.githubusercontent.com/20569/98827437-e081bc80-2404-11eb-8af3-39831b9f4aaa.png">

This is clearly incorrect, which you can see if you navigate to the metric detail:

https://glean-dictionary-dev.netlify.app/#!/apps/fenix/metrics/browser.search.ad_clicks

It's unclear to me right now whether this is a bug in the ETL or the display, but it's hopefully not too hard to fix.

**Comment by Iinh** [comment]
@wlach Could I work on this issue?

**Comment by wlach** [comment]
> @wlach Could I work on this issue?

For sure! Please go ahead.

**Comment by mhmohona** [comment]
In app page, this is happening for some other metric disruptions as well, not only for browser.search.ad_clicks.
