### ISSUE TITLE
Bugs and issues should be shortened in UI

### ISSUE THREAD

**Issue by wlach** [mozilla/glean-dictionary#191]
Right now we display the full URLs to bugzilla bugs and github issues. For example:

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/20569/98827888-5dad3180-2405-11eb-88a3-74d5c3cc9d57.png">

and:

<img width="656" alt="image" src="https://user-images.githubusercontent.com/20569/98827929-6b62b700-2405-11eb-9079-b4b7aa847960.png">

It would be nice to use an easily readable shorthand for these. For bugzilla, a nice convention @robhudson found for glam was:

`bugzil.la/{bug id}` (e.g. `bugzil.la/1234`)

For GitHub issues and pull requests, the convention is:

`mozilla/glean-dictionary#101`

Sometimes there are links to a specific bug comment in the form of a bookmark (e.g. `#c95`). In that case, we should append something to the end of the title (to make it clear that it's a specific comment being referenced). I think for Bugzillla we can just use the full bookmark (since it's relatively short). For GitHub, I'd suggest just appending `-comment` (as `#issuecomment-592187878` is pretty verbose and not overly descriptive).

[bugzil.la/1599877#c25](https://bugzil.la/1599877#c25)
[mozilla-mobile/fenix#6174-comment](https://github.com/mozilla-mobile/fenix/issues/6174#issuecomment-592187878)

In terms of implementation, I would write a small svelte component that takes a string as input and creates a small UI element with a properly formatted title and URL. Please write a story for it, in line with other components we've added recently (see e.g. #155)

**Comment by mhmohona** [comment]
Can I work on this issue?

**Comment by wlach** [comment]
> Can I work on this issue?

For sure!

**Comment by wlach** [comment]
@mhmohona Do you think you'll be able to work on this soon? It's ok if not, but we might want to assign it to someone else if that's the case.

**Comment by wlach** [comment]
I'm going to take this one, I think we actually need it done sooner than later as the UI around displaying issues (a key point) is a little confusing without this.
