### ISSUE TITLE
Seperate out "Pings" and "Metrics" into seperate tabs

### ISSUE THREAD

**Issue by wlach** [mozilla/glean-dictionary#193]
Currently we show "pings" and "metrics" on the app page one after another:

![image](https://user-images.githubusercontent.com/20569/99000546-73a31b00-2507-11eb-8b85-8cc51fd78c56.png)

This forces the user to scroll down and see more, which is a little awkward. One obvious approach here is to use a tabbed notebook interface, to let users show one or the other. I think in most cases the order should be "Metrics", then "Pings" (my hypothesis is that most of the time users want to scan through metrics, rather than pings)

This svelte repl shows the basic concept:

https://svelte.dev/repl/8e68120858e5322272dc9136c4bb79cc?version=3.7.0

To solve this issue, you want to do a couple things:

1. Create an equivalent set of components inside this app (I think the repl is simplistic enough that we can not worry too much about copyright), adding a short story in `stories` to test it.
2. Use it to streamline the app view

**Comment by wlach** [comment]
@Riju19 -- would you be interested in taking this on?

**Comment by Riju19** [comment]
Yes, absolutely!
