### ISSUE TITLE
Debugging locally on MacOS can break due to port 5000 being used by AirPlay

### ISSUE THREAD

**Issue by travis79** [mozilla/glean-dictionary#1998]
The default port that node serves the Glean Dictionary on is port 5000, this is also the same port that AirPlay uses. The weird part of this is that port 5000 works just fine in Safari and Chrome, it's only Firefox that seems to break by getting a 403 Forbidden response from `Server: AirTunes/745.13.4`.

Changing the package.json file under the `start` command to add `--port 8080` seems to resolve this for me by moving the port to a less contentious one.

**Comment by chutten** [comment]
See also lukeed/sirv#124 (fixed in sirv v2.0.0)
