### ISSUE TITLE
Add "i" information link for "Sampled" column on metric list page

### ISSUE THREAD

**Issue by travis79** [mozilla/glean-dictionary#2020]
Add i-circle information link to the "Sampled" column on the metrics detail page to inform users about:

- The meaning/intent of the column
- The possible values that can be seen there and their meanings

**Comment by Iinh** [comment]
Given that the majority of our metrics are not yet sampled, resulting in this column frequently displaying "Not Sampled," what are your thoughts on using a boolean checkbox instead? This checkbox would display sampled metrics when selected, as an alternative to using a column.

Something like this:

<img width="858" alt="Screenshot 2023-12-01 at 10 50 16 AM" src="https://github.com/mozilla/glean-dictionary/assets/28797553/cba59e79-52a6-421e-95cb-e4b98e0688af">

We could eventually transition this checkbox into a full column This is to minimize UI noise. And we can still add tooltip `i` information to the checkbox too.

**Comment by travis79** [comment]
That sounds like a great idea! This was intended to be iterated on so no worries about the timing of the suggestion. I'm always happy to receive advice on things like this 😄

**Comment by Iinh** [comment]
Awesome! I'll open a PR to make this change.
