### ISSUE TITLE
Display metric type and expiry date separately from the metric description

### ISSUE THREAD

**Issue by Riju19** [mozilla/glean-dictionary#211]
When we view a specific metric, the metric type and the expiry date get mixed up with the description. 

![image](https://user-images.githubusercontent.com/24811075/99885087-8250a700-2c58-11eb-86df-0f7b7d6b8c58.png)

We could probably display that as part of the table, or we above the table, in a format something like - 
 Metric Type: event / Expiry Date : 2020-09-01

**Comment by wlach** [comment]
I think the "metric type" is worth highlighting above the table (or whatever we wind up using later) but the expiry date should definitely go below the fold.

Possibly interesting as reference here is the rendered markdown documentation for glean apps: https://github.com/mozilla/mozregression/blob/master/docs/glean/metrics.md

**Comment by wlach** [comment]
@Riju19 assigning this to you under the assumption you'd like to work on it

**Comment by wlach** [comment]
This got fixed as part of #357 (forgot about this at the time, sorry)
