### ISSUE TITLE
Link back to metric and ping definitions in source control

### ISSUE THREAD

**Issue by wlach** [mozilla/glean-dictionary#223]
It is sometimes handy to be able to go *back* to the original definitions in GitHub (or other source repositories) where glean metrics and pings are defined (e.g. to fix a typo or make an edit). 

I would propose adding a "Defined in" field inside the metrics and ping pages that linked back to the metric and ping files at the appropriate line number. For example, for [the usage ping for mozregression](https://glean-dictionary-dev.netlify.app/#!/apps/mozregression/pings/usage), we would link back to:

https://github.com/mozilla/mozregression/blob/master/mozregression/pings.yaml#L4

The link name would be the unique part of the page after `/master/` (`mozregression/pings.yaml`)

Solving this issue would involve several steps:

1. Update the [glean_parser](https://github.com/mozilla/glean_parser/) to gather this information (this article on getting line number information from yaml files may prove useful: https://stackoverflow.com/questions/13319067/parsing-yaml-return-with-line-number) 
2. Gather this newly exposed data using glean-parser inside [probe-scraper](https://github.com/mozilla/probe-scraper/) and expose it.
3. Update our [own metadata gathering script](https://github.com/mozilla/glean-dictionary/blob/main/scripts/build-glean-metadata.py) to make use of this information.
4. Finally (the easy part) expose this data in the glean dictionary UI.

**Comment by Iinh** [comment]
@wlach Can I work on this?

**Comment by wlach** [comment]
> @wlach Can I work on this?

For sure! For (1) I would recommend reaching out to the Glean team on https://chat.mozilla.org/#/room/#glean:mozilla.org
