### ISSUE TITLE
Don't show expired metrics by default

### ISSUE THREAD

**Issue by mdboom** [mozilla/glean-dictionary#23]
Many of the probes in the existing probe dictionary are expired or deprecated (and they don't always have build end dates).  This causes confusion, since it might not be clear that no data will be available in those probes for currently-released products.  While the ability to access historical probes should always exist, we should optimize for what is presumably the common case of looking at new data flowing in.

This might include:

- A visually obvious identifier for deprecated or expired probes
- Not returning search results for expired probes (unless checking a box)
- Ranking search results by date of last update to the probe definition

**Comment by wlach** [comment]
👍 note that some probes seem to be inaccurately marked as expired, see mozilla/probe-dictionary#116

**Comment by wlach** [comment]
There are some things that need to move into place before we can tackle this, so is not a good issue for contributors. However, we should be able to tackle this in phase 1.

**Comment by wlach** [comment]
I think we can start implementing this. I think there are a few elements here:

1. We need to include expiry date information in the metrics summary we use on the application page (https://github.com/mozilla/glean-dictionary/blob/3bfedda171c13155ff89b75947a1636f4a8da5ab/scripts/build-glean-metadata.py#L66 and https://github.com/mozilla/glean-dictionary/blob/3bfedda171c13155ff89b75947a1636f4a8da5ab/scripts/build-glean-metadata.py#L58).
2. Then, we can provide a checkbox on the metrics page of an application that allows the user to "Show expired metrics" (unchecked by default). If the checkbox is unticked, then we should filter all the metrics by their expiry data-- any whose expiry date is less than the current data, should *not* be shown. If the checkbox is ticked, we should put a pill next to any metrics that are expired that says "expired".
3. On the metrics page itself, we should show the same pill saying expired.

This is analagous to the show deprecated applications on the front page:

![image](https://user-images.githubusercontent.com/20569/100151457-2ad85400-2e6f-11eb-875e-74550308ef4d.png)

And what we show on the application page:

![image](https://user-images.githubusercontent.com/20569/100152412-a8509400-2e70-11eb-8df2-08fb788be8d1.png)

**Comment by wlach** [comment]
#225 might be nice to fix before this one, it would probably reduce the work involved a bunch to make it work nicely on both the application and ping pages.

**Comment by Ankita13-code** [comment]
Hii! Can I work on this?

**Comment by wlach** [comment]
> Hii! Can I work on this @wlach ?

Yes, please go ahead. I think there should be enough information above to get started. I won't be around consistently for the next week, but feel free to ask in #glean-dictionary if you get stuck.

**Comment by wlach** [comment]
Hi @Ankita13-code! How's it going? We were hoping to fix this issue in the next few days, if you're not available right now I might need to assign it to someone else. If you need any help with it, feel free to reach out.

**Comment by Ankita13-code** [comment]
Hi @wlach! Actually my end semester examinations are going on these days and thus I won't be able to work on this issues for the rest of the january.Though I have made some progress in this and might complete it soon once I get back working. If this needs to be fixed urgently then you may assign it to someone else.

**Comment by wlach** [comment]
> Hi @wlach! Actually my end semester examinations are going on these days and thus I won't be able to work on this issue for the rest of the january. Though I have made some progress in this and might complete it soon once I get back to work on this. If this needs to be fixed urgently then you may assign it to someone else.

Hi Ankita, thanks for the update. I'm going to defer this to the next milestone for now, but we may need to assign to someone else in the next little bit depending on feedback. Fortunately there is no end of other things to work on in this project. 😄

**Comment by Iinh** [comment]
I'm going to work on this as I'm working on another related issue #65 and having this fixed would be really helpful.
