### ISSUE TITLE
Add comment sections to probe details

### ISSUE THREAD

**Issue by tdsmith** [mozilla/glean-dictionary#239]
This is an off-the-wall idea that came up in the data science team meeting today: it would be super helpful if data scientists had a place to leave comments on probes to discuss their behaviour and share warnings for future travellers!

Maybe the answer is "just use Bugzilla," or maybe there's another place, but this is a place that many data scientists look and so it seems like it could profitably live here.

Moderation or authentication is an obvious concern; possibly this could link out to Discourse threads or some other already-moderated Mozilla space, but it would be great if we could see _whether_ there's a comment available, and ideally what it is.

**Comment by wlach** [comment]
I'm not sure if/when we'll do this for the glean dictionary, but if it's going to happen anywhere, it's going to happen here. 😄
