### ISSUE TITLE
Refine the metric page (transferred from old glean dictionary)

### ISSUE THREAD

**Issue by Dexterp37** [mozilla/glean-dictionary#241]
cc @spasovski 

I know this is a pre-alpha, but I thought to share my feedback on this anyway :-) There's a few small nits that I believe would make this page a bit more digestible (see the relative colored numbers on the image):

1. I'd change the label to resonate with the wording in [the Glean Docs](https://mozilla.github.io/glean/book/user/metric-parameters.html), i.e. `relevant bugs`
1a. It also might make sense to drop the links from there, and just use a numbered list of links, for example, something that would look like this markdown `[1](link to the first bug/GH issue), [2](...)`.
2. It would be great to have tooltips/question marks icons like in GLAM to remind users what these entries mean. They are documented in the Glean docs and, for example, `lifetime` is usually confusing.
3. Instead of `Timing_distribution`, this should probably drop the `_` and also link to the proper glean docs (e.g. https://mozilla.github.io/glean/book/user/metrics/timing_distribution.html) -  note that the name of the metric type is also the same name of the documentation for that metric type. This is on purpose, so that you can do `https://mozilla.github.io/glean/book/user/metrics/{metric_type_name}.html`

![image](https://user-images.githubusercontent.com/883721/87171792-7c72ae80-c2d3-11ea-8456-290da0c4cc8b.png)

**Comment by wlach** [comment]
Not sure how much of this feedback is still relevant, but moving this here just to make sure we're not missing anything.

**Comment by wlach** [comment]
Reading over this, I think we'll be good as far as the asks in this issue when #323 is complete.
