### ISSUE TITLE
"Includes client identifier" field incorrect on ping page

### ISSUE THREAD

**Issue by wlach** [mozilla/glean-dictionary#243]
The Fenix baseline ping *definitely* contains a client identifier, but the UI is incorrectly saying it doesn't have one:

![image](https://user-images.githubusercontent.com/20569/101093940-97e39c00-3589-11eb-9f11-d0d74218ea5b.png)

https://glean-dictionary-dev.netlify.app/#!/apps/fenix/pings/baseline

The bug is somewhere in here, most likely:

https://github.com/mozilla/glean-dictionary/blob/main/src/pages/PingDetail.svelte

Looking at the JSON being fetched by this view may provide some clues:

https://glean-dictionary-dev.netlify.app/data/fenix/pings/baseline.json

**Comment by singhvaishnavi** [comment]
@wlach can I work on this?

**Comment by wlach** [comment]
Yes, please go ahead!

**Comment by wlach** [comment]
Fixed by #261
