### ISSUE TITLE
Opening links in new tabs leads to a 404

### ISSUE THREAD

**Issue by fbertsch** [mozilla/glean-dictionary#257]
Steps to reproduce:
1. Start in an app, e.g. https://glean-dictionary-dev.netlify.app/#!/apps/firefox-ios-beta
2. Control+click any of the metrics on that page, and the new tab is a 404: https://glean-dictionary-dev.netlify.app/apps/firefox-ios-beta/metrics/app.opened_as_default_browser

Clicking on it in _not_ a new tab does not 404.

**Comment by wlach** [comment]
Should be fixable by adding a `_redirects` file. We should also move away from using hash-based routing (inconsitently):

https://docs.netlify.com/routing/redirects/rewrites-proxies/#history-pushstate-and-single-page-apps
