### ISSUE TITLE
Add "type" to metric summary

### ISSUE THREAD

**Issue by wlach** [mozilla/glean-dictionary#258]
From @fbertsch:

The first prototype included "types" of each metric on the summary page, we should do the same in this version:

![image](https://user-images.githubusercontent.com/20569/101646988-364a8400-3a06-11eb-93d1-6e010cfc2ad7.png)

**Comment by mhmohona** [comment]
Will it be like this? 
![image](https://user-images.githubusercontent.com/14244685/101880070-879c7400-3bbc-11eb-8f16-ba7fb8a8e0d0.png)

**Comment by wlach** [comment]
@mhmohona We'd want to add this information to the metrics list on the app page (example: https://glean-dictionary-dev.netlify.app/#!/apps/fenix) and the ping page (example: https://glean-dictionary-dev.netlify.app/#!/apps/fenix/pings/activation)

Related: @Iinh is going to consolidate the display of metrics into one component in #225 -- at which point you'd only need to add this to one component and get it displayed in both. It might be best to hold off on this until that work is complete. If you're looking for something to work on in the mean time, #243 is up for grabs. 😄

**Comment by wlach** [comment]
@mhmohona Update: #225 has landed, so please go ahead and work on this! You'll want to modify https://github.com/mozilla/glean-dictionary/blob/main/src/components/ItemList.svelte and the things that call it.

**Comment by wlach** [comment]
@mhmohona do you think you'll be able to work on this any time soon? I think we want this implemented sooner than later, so I might pick this up if you're not available.

**Comment by mhmohona** [comment]
@wlach, I am working on it. Hoping by tomorrow or the day after tomorrow I will be able to make RP. Sorry for the delay. :(

**Comment by Iinh** [comment]
Hi @mhmohona I was wondering if there's any progress with this. If you don't mind I can take this one up if you're busy :)

**Comment by Iinh** [comment]
Assigning myself after talking with @mhmohona. Thank you Mahfuza for your help!
