### ISSUE TITLE
The list of pages overflows its container in Firefox Nightly

### ISSUE THREAD

**Issue by Dexterp37** [mozilla/glean-dictionary#259]
![image](https://user-images.githubusercontent.com/883721/101761464-767c3600-3adc-11eb-85b8-e67e79358dc6.png)

The gray strip of numbers at the bottom of the page seems to be overflowing outside of its container? Should this be contained in the "Metrics" pane?

**Comment by wlach** [comment]
Thanks for filing! This is a duplicate of #246
