### ISSUE TITLE
Firefox for Android Metrics should link out to GLAM

### ISSUE THREAD

**Issue by wlach** [mozilla/glean-dictionary#279]
For example, we should have a link on:

https://glean-dictionary-dev.netlify.app/apps/fenix/metrics/geckoview.page_reload_time

To:

https://glam.telemetry.mozilla.org/fenix/probe/geckoview_page_reload_time/explore

We should do this for all the channels, not just nightly:

* https://glean-dictionary-dev.netlify.app/apps/firefox-android-release/metrics/geckoview.page_reload_time -> https://glam.telemetry.mozilla.org/fenix/probe/geckoview_page_reload_time/explore?app_id=release
* https://glean-dictionary-dev.netlify.app/apps/firefox-android-beta/metrics/geckoview.page_reload_time -> https://glam.telemetry.mozilla.org/fenix/probe/geckoview_page_reload_time/explore?app_id=beta (*)

Since unfortunately GLAM is still behind LDAP (I think eventually the plan is to make at least parts of it public) this is probably best done by either someone at Mozilla or an NDA'd contributor with LDAP access.

(*) I *think* `firefox-android-beta` is the right app id for this channel, though we're currently marking it as deprecated

**Comment by robhudson** [comment]
I'd be happy to work on this if you'd like.

**Comment by wlach** [comment]
> I'd be happy to work on this if you'd like.

That would be awesome! I'll assign this to you.

**Comment by wlach** [comment]
For a first implementation, I'm fine with hardcoding the references to GLAM in the source to this project. We should figure out a more principled way of doing this in the future though.
