### ISSUE TITLE
Add tooltips with contextual help for application, ping and metric fields

### ISSUE THREAD

**Issue by wlach** [mozilla/glean-dictionary#293]
One trick we've been using with internal dashboards is to have help icons which, on hover, pop up contextual help to give people an idea of what the field means. See for example, the [desktop funnel dashboard](https://github.com/mozilla/funnel):

![image](https://user-images.githubusercontent.com/20569/102930096-cdcdbf00-4469-11eb-90ab-177a19e3b920.png)

We should do something similar in the Glean dictionary. For example on the metrics page, we could put a help icon beside each of these fields:

![image](https://user-images.githubusercontent.com/20569/102930263-19806880-446a-11eb-90e8-77c1ea2d8136.png)
https://glean-dictionary-dev.netlify.app/apps/burnham/metrics/mission-status

Many of the metric parameters are defined in the Glean documentation. For example, metric parameters are defined here:

https://mozilla.github.io/glean/book/user/metric-parameters.html

I think we can probably just lift the definitions and put them in here verbatim. It may be good idea to also *link* to their definition in the glean documentation, which people could visit for further reference (the old glean dictionary [attempts to do this](https://glean-dictionary.netlify.app/?metric=perf_awesomebar_bookmark_suggestions), although it is incorrect in some places). You can look at the code here:

https://github.com/mozilla/probe-dictionary/blob/glean-only/src/components/GleanProbeDetails.svelte#L105

For rendering the tooltip, we can probably just use a library like [sveltejs-tippy](https://github.com/mdauner/sveltejs-tippy) -- maybe best to define our own component based on it and create a story, as usual.

**Comment by Fenn-CS** [comment]
Picking this up.
