### ISSUE TITLE
Add Git version information to footer

### ISSUE THREAD

**Issue by wlach** [mozilla/glean-dictionary#295]
When working on [iodide](https://alpha.iodide.io) I added a handy feature that would tell you the version that was deployed in the footer. We should add something similar for the glean dictionary. This will become more important as we move to production deploys and it becomes less obvious what version is in use.

![image](https://user-images.githubusercontent.com/20569/102936511-4c305e00-4476-11eb-9e41-ad3a39f110dd.png)

This is pretty simple in outline:

* Run `git rev-list HEAD --max-count=1` from rollup and capture the result into a variable
* Use the replace plugin (here's an existing example: https://github.com/mozilla/glean-dictionary/blob/b7ae2ced6684bacbaed49bd99ef21f0b75f1c91e/rollup.config.js#L53) to inject it into the footer.

The current footer will probably change a bunch in the near future, but it's probably fine to just put the data next to the existing items on the right for now.

**Comment by Fenn-CS** [comment]
Hello @wlach please assign this to me.

**Comment by wlach** [comment]
> Hello @wlach please assign this to me.

For sure, in the future don't worry about being explicitly assigned -- you can just let people know you're working on something and we'll figure it out from there.
