### ISSUE TITLE
Restyle AppAlert

### ISSUE THREAD

**Issue by Iinh** [mozilla/glean-dictionary#316]
After switching to Protocol, `AppAlert` is not looking very good: https://glean-dictionary-dev.netlify.app/apps/glean-js. 

[The original vision ](https://github.com/mozilla/glean-dictionary/issues/116#issuecomment-708988953) for the banner was more like below.

<img width="1391" alt="96096713-6bd46480-0ed0-11eb-9f81-9ee8fd799923" src="https://user-images.githubusercontent.com/28797553/104535908-e134fb80-55cb-11eb-97f4-d934a72651a0.png">

I think we should use another color other than gray -- one that shows this is an alert -- for the banner. Let's choose one from this list: https://protocol.mozilla.org/fundamentals/color.html

**Comment by wlach** [comment]
That sounds about right. I would probably refactor AppAlert into a more generic Alert class. It might make sense to use [the protocol notification bar component](https://protocol.mozilla.org/patterns/molecules/notification-bar.html) here (probably without the close button).
