### ISSUE TITLE
Specify the dependencies in `package.json`

### ISSUE THREAD

**Issue by Iinh** [mozilla/glean-dictionary#317]
https://github.com/mozilla/glean-dictionary/pull/312#discussion_r555799026

We should reorganize `package.json` and specify what packages needed for production (`"dependencies"`) versus local development (`"devDependencies"`).

**Comment by wlach** [comment]
I think for a webapp like this the distinction between `devDependencies` and `dependencies` is not so important -- we're not publishing it to npm or anything. That said, it makes sense to be consistent. In this case, I think technically everything should just be a `devDependency`.
