### ISSUE TITLE
Consider updating HTML title to better reflect the page visited

### ISSUE THREAD

**Issue by robhudson** [mozilla/glean-dictionary#321]
If I have multiple glean dictionary URLs open in my browser they all appear the same. Consider some naming convention that reflects the page the user is on, whether it's a metric detail page or app detail, to help differentiate.

**Comment by wlach** [comment]
This would be a good one to fix. Stackoverflow suggests https://stackoverflow.com/a/59028538 -- unless you have better ideas Rob?

**Comment by robhudson** [comment]
Yep, I'm doing the same in GLAM...
https://github.com/mozilla/glam/blob/c140fa12c833210c2ba8d9aee95e3800296e81c0/src/routing/wrappers/Layout.svelte#L17-L20

**Comment by wlach** [comment]
This is actually rather important for usability.

**Comment by Iinh** [comment]
I'm going to work on this one
