### ISSUE TITLE
Fix footer to the bottom of the page

### ISSUE THREAD

**Issue by Iinh** [mozilla/glean-dictionary#322]
Right now the footer is not sticky, it jumps up when the content length changes, and leaves a white gap at the bottom.

<img width="1263" alt="Screen Shot 2021-01-14 at 10 34 40 AM" src="https://user-images.githubusercontent.com/28797553/104639437-47695f00-565c-11eb-8383-cc3b6be5279f.png">

Example:
https://glean-dictionary.protosaur.dev/apps/fenix/metrics/about_page-libraries_tapped

**Comment by wlach** [comment]
@Iinh is this something you could pick up when you're between tasks? I'm not sure what the "state of the art" is for fixing this type of issue, but here's one stackoverflow entry with various answers (the pure CSS approach is what you want):

https://stackoverflow.com/a/21207313
