### ISSUE TITLE
Glean Dictionary incorrectly stating historical data

### ISSUE THREAD

**Issue by fbertsch** [mozilla/glean-dictionary#354]
[This probe](https://dictionary.protosaur.dev/apps/fenix/metrics/browser_search_with_ads) is an example problem. It indicates that it is sent in two pings: baseline and metrics. However the [probe-info-service](https://probeinfo.telemetry.mozilla.org/glean/fenix/metrics) tells a different story, that it was only sent on the baseline ping in the spring of 2020, which means that now almost _no_ baseline pings would include it (only those from very old clients).

@wlach suggested that we should be matching the definition to versions, which would require use of the `git-commits` (but only for a linear history, I believe).

**Comment by wlach** [comment]
@fbertsch On reflection, maybe a quick workaround is for the glean dictionary to just show what pings are sent in the current version? Longer term, we can figure out an interface for browsing/viewing metric history if there's sufficient need / demand.
