### ISSUE TITLE
Metrics table for org_mozilla_firefox (fenix) is broken due to CORS

### ISSUE THREAD

**Issue by acmiyaguchi** [mozilla/glean-dictionary#373]
Going to https://dictionary.protosaur.dev/apps/fenix/tables/metrics leads to this error:

![image](https://user-images.githubusercontent.com/3304040/106669919-3fb52000-6561-11eb-906b-c466bc227758.png)

**Comment by wlach** [comment]
Hmm, seems to work for me?

![image](https://user-images.githubusercontent.com/20569/106776998-93cc0d00-6612-11eb-8cb2-270698000950.png)

Feel free to reopen if there's something I'm missing.

**Comment by acmiyaguchi** [comment]
This is still broken for me, I'm getting a CORS issue specifically after looking in the console:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://raw.githubusercontent.com/mozilla-services/mozilla-pipeline-schemas/generated-schemas/schemas/org-mozilla-fenix/metrics/metrics.1.bq. (Reason: CORS request did not succeed).
```

**Comment by Iinh** [comment]
I'm also getting a CORS error, not with just `fenix`, but any `metrics` BQ table. For example:

https://dictionary.protosaur.dev/apps/firefox-ios-beta/tables/metrics
https://dictionary.protosaur.dev/apps/firefox-android-release/tables/metrics
https://dictionary.protosaur.dev/apps/firefox-focus-ios/tables/metrics
https://dictionary.protosaur.dev/apps/firefox-android-beta/tables/metrics

<img width="890" alt="Screen Shot 2021-02-03 at 10 21 14 AM" src="https://user-images.githubusercontent.com/28797553/106791346-a857d780-6609-11eb-96a3-05308e79d67a.png">

<img width="894" alt="Screen Shot 2021-02-03 at 10 17 54 AM" src="https://user-images.githubusercontent.com/28797553/106791166-6d55a400-6609-11eb-8955-3b4c2f7c8662.png">
<img width="885" alt="Screen Shot 2021-02-03 at 10 13 53 AM" src="https://user-images.githubusercontent.com/28797553/106791188-75addf00-6609-11eb-90d8-128ac8d69e61.png">

**Comment by wlach** [comment]
Likely github changed their CORS policy. I'll investigate.

**Comment by acmiyaguchi** [comment]
This doesn't affect netlify, but it does protosaur. It's kind of strange that this is the case.

**Comment by wlach** [comment]
> This doesn't affect netlify, but it does protosaur. It's kind of strange that this is the case.

I can't reproduce on either, even with a fresh cache. Can you show me what the headers look like in the network panel when it fails?

**Comment by Iinh** [comment]
@acmiyaguchi I think the ad blocker might be the villain here... I'm using [uBlock Origin](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/), I can load metrics table now if I turn my ad blocker off.

**Comment by acmiyaguchi** [comment]
I can confirm that I can load metrics after turning off my ad blocker.

**Comment by Iinh** [comment]
Should we add some kind of warning/error message to the metrics table page to let the users know they need to turn off their ad blocker if they encounter CORS issue?

**Comment by wlach** [comment]
> Should we add some kind of warning/error message to the metrics table page to let the users know they need to turn off their ad blocker if they encounter CORS issue?

I think we should probably download the JSON file from github at build-time, then serve it locally. This is probably a bug in uBlock, but at the same time we probably shouldn't rely on GitHub serving the right CORS headers. I can look into fixing this in the next day or so.
