### ISSUE TITLE
Use sourcegraph to search for code in repos not indexed by searchfox

### ISSUE THREAD

**Issue by wlach** [mozilla/glean-dictionary#404]
In #339 @Iinh added support for searching for glean metric definitions using searchfox. However, not everything we care about is currently indexed by searchfox.

Seperately, @Iinh found a great service called sourcegraph which indexes at least some of these repositories. For example, mozregression:

https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/mozilla/mozregression%24+&patternType=literal

For these cases, we should provide links to sourcegraph. 

This is on the complex end of things for a good first bug, but should be doable. Fixing this issue would involve:

* Looking at how @Iinh implemented things in #339
* Implementing similar functionality for getting links to sourcegraph (note we would *only* return links to sourcegraph where we do not have a searchfox link, since searchfox is more familiar and probably better for those cases) and putting them in the metadata table.

**Comment by jcads** [comment]
Hi, I would like to work in this issue.

My approach would be to add a sourcegraph Map with repos that are not in the [searchfoxMap](https://github.com/mozilla/glean-dictionary/blob/65292aee2ab7a68dbc2a06483ae5ba1c46c0e4d0/src/formatters/searchfox.js#L3). 

Then add an `else` statement in [line 63](https://github.com/mozilla/glean-dictionary/blob/65292aee2ab7a68dbc2a06483ae5ba1c46c0e4d0/src/formatters/searchfox.js#L63) of [searchfox.js](https://github.com/mozilla/glean-dictionary/blob/65292aee2ab7a68dbc2a06483ae5ba1c46c0e4d0/src/formatters/searchfox.js) that returns the sourcegraph URL search query of the given metric. Of course, we would need to rename `searchfox.js` to something more generalized like `metricLink.js`.

**Comment by wlach** [comment]
@jcads that would be great! I haven't looked at the code in question in a while, but in outline what you say makes sense to me.

**Comment by jcads** [comment]
I'll make a PR on this once #459 gets merged.

**Comment by jcads** [comment]
@wlach, should we change `Searchfox` to a more general title like `Uses`? Or just change the title dynamically? Either `Sourcegraph` or `Searchfox`, based on where the metric was indexed.

![image](https://user-images.githubusercontent.com/50954098/111251693-b3f7de80-864a-11eb-9bc0-0b5a017da580.png)

What do you think?

**Comment by jcads** [comment]
> @wlach, should we change `Searchfox` to a more general title like `Uses`? Or just change the title dynamically? Either `Sourcegraph` or `Searchfox`, based on where the metric was indexed.
> 
> ![image](https://user-images.githubusercontent.com/50954098/111251693-b3f7de80-864a-11eb-9bc0-0b5a017da580.png)
> 
> What do you think?

I just left this as is in the PR #468.
