### ISSUE TITLE
Better ordering of applications on main (application) page

### ISSUE THREAD

**Issue by wlach** [mozilla/glean-dictionary#456]
Currently we display the applications in sort-order, which is not ideal. Ideally we would have some heuristic based on an application's relative popularity (e.g. number of ping submissions in the last week), though a manually curated ordering might do in a pinch.

**Comment by Iinh** [comment]
Let's try manual curation as a first pass. I'm not familiar with Mozilla products enough to know which ones are the most popular (I guess fenix and firefox ios are probably top 2, and desktop once fog migration is done?) How should I order them?

**Comment by wlach** [comment]
> Let's try manual curation as a first pass. I'm not familiar with Mozilla products enough to know which ones are the most popular (I guess fenix and firefox ios are probably top 2, and desktop once fog migration is done?) How should we order them?

Yup:

![image](https://user-images.githubusercontent.com/20569/119855433-e5f5ae80-bedf-11eb-9dd5-07d7acd29d6e.png)

I would probably just do:

1. Firefox Desktop
2. Firefox Android
3. Firefox iOS

Then everything else
