### ISSUE TITLE
Searchfox links for metrics not displaying for multi-worded application names

### ISSUE THREAD

**Issue by jcads** [mozilla/glean-dictionary#458]
## The Bug
I came across this bug while working on #404. 

Currently, the links doesn't work because the separator used in `searchfoxMap` in [searchfox.js](https://github.com/mozilla/glean-dictionary/blob/65292aee2ab7a68dbc2a06483ae5ba1c46c0e4d0/src/formatters/searchfox.js) is `-`, like so -- `"reference-browser": "reference-browser"`. 

The link doesn't work because the [`params.app`](https://github.com/mozilla/glean-dictionary/blob/65292aee2ab7a68dbc2a06483ae5ba1c46c0e4d0/src/pages/MetricDetail.svelte#L209) passed in `getSearchFox` uses snake_case.
https://github.com/mozilla/glean-dictionary/blob/65292aee2ab7a68dbc2a06483ae5ba1c46c0e4d0/src/pages/MetricDetail.svelte#L209

_works in Fenix_
![image](https://user-images.githubusercontent.com/50954098/111063604-9a3f8580-84ea-11eb-99ba-80e29b904d08.png)

_doesn't work in Reference Browser_
![image](https://user-images.githubusercontent.com/50954098/111063585-898f0f80-84ea-11eb-9c41-3f47afbc07b3.png)

## The Solution
Replace the keys in `searchfoxMap` with snake_casing.

_After making the change_
![image](https://user-images.githubusercontent.com/50954098/111063790-9a8c5080-84eb-11eb-85db-e8fb248e89cc.png)

**Comment by jcads** [comment]
This is an easy fix. Should make a PR?

**Comment by wlach** [comment]
@jcads please go ahead! Just a note, I may not be able to review it for a couple days.
