### ISSUE TITLE
Provide more help on how to access BigQuery resources

### ISSUE THREAD

**Issue by wlach** [mozilla/glean-dictionary#469]
This type of query doesn't work:

```sql
SELECT AVG(metrics.counter.metrics_top_sites_count)
FROM `mozdata`.org_mozilla_fenix.metrics
WHERE DATE(submission_timestamp) = '2021-01-01'
```

It seems like BigQuery gets confused when the name of a column is the same as the name of the table. For all metrics and events tables, we should prefix the column name in our BigQuery suggestion with the table name. I.e. we should suggest that people use `metrics.metrics.count.metrics_top_sites_count`.

See this slack thread for more context: https://mozilla.slack.com/archives/C4D5ZA91B/p1616015390007400

This is also relevant in the context of mozilla/data-docs#619, which I'm trying to finish up.

**Comment by wlach** [comment]
> It seems like BigQuery gets confused when the name of a column is the same as the name of the table. For all metrics and events tables, we should prefix the column name in our BigQuery suggestion with the table name. I.e. we should suggest that people use `metrics.metrics.count.metrics_top_sites_count`.

On second think, not actually sure we should do that. Maybe we should just link to the bigquery tutorial (in the PR above) from the BigQuery help icon.

**Comment by chichi012** [comment]
Hi @wlach I'm working on this in #732 
However, I have not been able to test this locally. Can you advise on the best way to go about testing?

**Comment by Iinh** [comment]
Hi @chichi012, thank you for taking this up. @wlach is out this month so I'll be reviewing your PR instead :) Were you able to set up a local instance of Glean Dictionary using [this guide](https://github.com/mozilla/glean-dictionary#getting-started)? The README also has information on how to run tests after you finish setting up locally. Hope that clarifies 🙂

**Comment by chichi012** [comment]
Thank you @Iinh. I was able to set up the instance of Glean Dictionary using the guide and ran the test using `npm run test:jest`. But I wasn't able to see the UI changes I made in my PR.
