### ISSUE TITLE
Investigate storybook for svelte

### ISSUE THREAD

**Issue by wlach** [mozilla/glean-dictionary#472]
There's a new release of storybook for svelte which seems to have some nice features: https://storybook.js.org/blog/storybook-for-svelte/

Worth investigating what it would take to upgrade to it, as I think it would make the experience of writing stories for our components easier.

**Comment by Iinh** [comment]
I'm currently working on using Storybook for Svelte with SvelteKit.

**Comment by Dexterp37** [comment]
I believe we have this now. @Iinh feel free to re-open if closing is not correct :)
