### ISSUE TITLE
Markdown with angle brackets in it doesn't get translated to html correctly

### ISSUE THREAD

**Issue by wlach** [mozilla/glean-dictionary#476]
See: https://dictionary.protosaur.dev/apps/fenix/metrics/browser_search_with_ads

![image](https://user-images.githubusercontent.com/20569/112214805-03fc1580-8bf6-11eb-94bc-94add617608d.png)

Underlying JSON: https://dictionary.protosaur.dev/data/fenix/metrics/browser_search_with_ads.json

My guess is that the problem is somewhere in our usage of the markdown library here: https://github.com/mozilla/glean-dictionary/blob/main/src/components/Markdown.svelte

After fixing, would be good to add a testcase to the story: https://github.com/mozilla/glean-dictionary/blob/main/stories/markdown.stories.js

@jcads Any interest in this one? 😄

**Comment by jcads** [comment]
Hey @wlach, thanks for the ping. 

Kindly assign this one to me. I'll definitely get back to you about writing the test cases.
