### ISSUE TITLE
“Did Not Connect: Potential Security Issue” error when loading the site

### ISSUE THREAD

**Issue by Iinh** [mozilla/glean-dictionary#482]
The error:

<img width="710" alt="Screen Shot 2021-03-25 at 9 06 18 PM" src="https://user-images.githubusercontent.com/28797553/112576135-ef16b200-8dae-11eb-81e5-fd15cf9b5d78.png">

**Comment by wlach** [comment]
Thanks @Iinh -- this is an operations issue. I filed a bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1701246

**Comment by Iinh** [comment]
Looks like this issue has been solved.
