### ISSUE TITLE
Add last deploy date to footer

### ISSUE THREAD

**Issue by wlach** [mozilla/glean-dictionary#495]
In #297 we added git information to the footer in the glean dictionary. It would also be nice to provide the last updated date, to give people a hint on how up to date the glean dictionary is with the information that we're getting from https://probeinfo.telemetry.mozilla.org and https://mozilla.github.io/glean-annotations/ (#494 will add nightly deploys)

Rough steps to solving this:

1. Generate a human-readable date in the rollup script (`rollup.config.js`) like "May 1st 2021"
2. Add it into the footer (`src/components/Footer.svelte`)

The end result should be a footer that says something like:

```
Last updated May 1st 2021

Alpha Software - revision 7a0a758dc3
...
```

**Comment by yatharthMogra** [comment]
hey @wlach I would like to work on this issue

**Comment by wlach** [comment]
Please go ahead! Let us know if you need any help.

**Comment by wlach** [comment]
Hey @chichi012, #766 isn't quite right-- it's not actually the git date we want, but the last *deploy time* for the data the Glean Dictionary is using. Sorry, I probably could have specified this better given that this was marked as a good first issue. 

In any case, you can get that deploy time data here (as JSON):

https://probeinfo.telemetry.mozilla.org/firefox/general

We should be able to pretty reliably get this data via curl (installed on most machines). To do that, we'd change the line around here:

https://github.com/mozilla/glean-dictionary/blob/901b2e578540d7cf6af4fc9f10d0b5e62b943bac/rollup.config.js#L77

To something like:

```js
      __LAST_UPDATED_TIME__: execSync(
        "curl --compressed https://probeinfo.telemetry.mozilla.org/firefox/general"
      )
```

From there, you can cast it to json (via `JSON.parse`) then parse out the date. While we're here, could we make the date link out to https://protosaur.dev/mps-deploys/ (which gives more detailed documentation on when the schema data was last updated)

Let me know if you're interested in working on this. If not, I can take care of it.

**Comment by chichi012** [comment]
Thanks for the feedback @wlach . I would love to give it another try
