### ISSUE TITLE
Persist pagination state in URL

### ISSUE THREAD

**Issue by wlach** [mozilla/glean-dictionary#528]
Just as we persist search strings and expired states (see #512), we should also persist the page that the user has navigated to (if any):

https://dictionary.protosaur.dev/apps/fenix?itemType=metrics&showExpired=1&page=3

This is a bit of a tricky one (it requires understanding the Glean Dictionary's URL persistence model, which is based on [svelte stores](https://svelte.dev/tutorial/writable-stores)) but might make an interesting issue for a motivated contributor to work on. Feel free to ping us in the channel if interested.

**Comment by harnaman-hk** [comment]
Hi @wlach! I would like to work on this issue

**Comment by wlach** [comment]
> Hi @wlach! I would like to work on this issue

Awesome! Please go ahead and let us know if you run into issues on the Glean Dictionary channel.
