### ISSUE TITLE
`app_channel` annotation not showing in Glean Dictionary

### ISSUE THREAD

**Issue by chutten** [mozilla/glean-dictionary#547]
I was showing off the Glean Dictionary's new annotation features, but noticed that the annotation I added for `app_channel` [wasn't showing](https://dictionary.protosaur.dev/apps/firefox_desktop/metrics/app_channel).

Other annotations (like the ["fog-validation" ping](https://dictionary.protosaur.dev/apps/firefox_desktop/pings/fog-validation) and [Firefox iOS' `app.opened_as_default_browser`](https://dictionary.protosaur.dev/apps/firefox_ios/metrics/app_opened_as_default_browser)) are showing, so it doesn't appear to be a global fault.

**Comment by wlach** [comment]
This is actually an issue with the Glean Dictionary. Happily fairly easy to fix.
