### ISSUE TITLE
Ad blocker blocks metric names that start with `metrics`

### ISSUE THREAD

**Issue by Iinh** [mozilla/glean-dictionary#550]
Metric names that start with `metrics`, such as:

[metrics.activity_state_provider_error](https://dictionary.protosaur.dev/apps/fenix/metrics/metrics_activity_state_provider_error)

[metrics.adjust_network](https://dictionary.protosaur.dev/apps/fenix/metrics/metrics_adjust_network)

[metrics.distribution_id](https://dictionary.protosaur.dev/apps/fenix/metrics/metrics_distribution_id)

are currently blocked by uBlock Origin. 

<img width="1268" alt="CleanShot 2021-04-26 at 08 51 27@2x" src="https://user-images.githubusercontent.com/28797553/116112668-9e73cc80-a66c-11eb-8142-62d859dfba63.png">

<img width="627" alt="CleanShot 2021-04-26 at 08 51 49@2x" src="https://user-images.githubusercontent.com/28797553/116112711-aaf82500-a66c-11eb-9b22-485e70ab90b2.png">

Looks like it doesn't like the google analytics tracker that we use, however I'm not sure why it only targets metric name that starts with `metrics`. Other metric pages seem to work fine.

**Comment by wlach** [comment]
Yeah, I knew it was blocking google analytics but didn't know about this. Wow. Looks like it's blocking loading the JSON resource:

![image](https://user-images.githubusercontent.com/20569/116114964-e0f6d280-a687-11eb-85ca-dc50919bb502.png)

IMO this is a bug in uBlock origin.

We can probably work around it by giving these files some other name. Prepending something like `data_` to the JSON files may even be enough. @Iinh do you want to give this a try when you have a moment?

**Comment by Iinh** [comment]
Yes let me give it a try!
