### ISSUE TITLE
Add "Older Firefox desktop telemetry" (or similar) link to the original probe dictionary

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/glean-dictionary#557]
Some folks might land on the Glean dictionary when they're looking for information on an old school telemetry style probe... it'd probably be a good idea to put a link to the older probe dictionary in one or more strategic locations. Possibly the front page, almost certainly on the search results page, especially when the search results are empty. "Can't find what you're looking for? Non-Glean probes can be found in the original _Probe Dictionary_" or something.

**Comment by rafrombrc** [comment]
Looking at the home page, the description text under the "Firefox for Desktop" application is probably a good place for this link... we could explain that the app you're looking at will only cover Glean probes and include a link.

**Comment by wlach** [comment]
Yeah, I think the warning should probably appear on this page:

https://dictionary.telemetry.mozilla.org/apps/firefox_desktop?itemType=metrics

I think we can implement this as a special kind of structured annotation ("warning") which we might be able to apply to other applications in the future.
