### ISSUE TITLE
Dictionary should show documentation of event extra_keys

### ISSUE THREAD

**Issue by tdsmith** [mozilla/glean-dictionary#585]
The description at https://dictionary.telemetry.mozilla.org/apps/fenix/metrics/events_browser_menu_action isn't as helpful as it could be because the extra_values described in the definition at https://github.com/mozilla-mobile/fenix/blob/7cdf7a54df15d96b6f68b73be8140abb2223109d/app/metrics.yaml#L193 hold most of the event's content.

The link to the definition is really great here, though!

**Comment by wlach** [comment]
Yep, we should add this. @Iinh do you want to take a look at this one? The [glean documentation](https://mozilla.github.io/glean/book/reference/metrics/event.html) on events might be a helpful resource to use when thinking about how to display this information.
