### ISSUE TITLE
When landing on Glean Dictionary it's not clear what it is

### ISSUE THREAD

**Issue by chutten** [mozilla/glean-dictionary#587]
The Glean Dictionary index doesn't describe what it's about, throwing you directly at the app tiles.

This is great for folks who already know what it is, but anyone being told to consult it for the first time might be a bit lost.

I think (and I'm often wrong) the Glean Dictionary would benefit from some front matter. Maybe

> The Glean Dictionary documents the data collected by [Mozilla](https://mozilla.org/) projects that use [Glean](https://mozilla.github.io/glean/book/index.html). Click on a project below to browse its data catalogue. If you have questions, please ask in the [Glean Dictionary channel on Mozilla's Matrix](https://chat.mozilla.org/#/room/#glean-dictionary:mozilla.org).

**Comment by wlach** [comment]
This seems like a good idea -- a little onboarding can go a long way. Let me implement something real quick.
