### ISSUE TITLE
Improve display of labels

### ISSUE THREAD

**Issue by wlach** [mozilla/glean-dictionary#602]
We're still using a pretty primitive svelte component we've called "Pill" for rendering labels in the app:

![image](https://user-images.githubusercontent.com/20569/118706808-cf689c80-b7e7-11eb-9d14-c8863ffa3548.png)

https://github.com/mozilla/glean-dictionary/blob/9f27d440ceb6977997dd6fc87a7e0dd067a5b33e/src/components/Pill.svelte

It would be nice to improve the look of them to be more consistent with the protocol library we're using. I actually filed an issue about this here: https://github.com/mozilla/protocol/issues/689 -- but am also open to working on a Glean Dictionary implementation specifically if it looks like doing it upstream doesn't make sense for one reason or another.

**Comment by Iinh** [comment]
I'll take this up. I added some UI improvements in the SvelteKit migration that I'm working on, it would make sense to tackle this too.
