### ISSUE TITLE
Run ETL code after a schema deploy

### ISSUE THREAD

**Issue by wlach** [mozilla/glean-dictionary#61]
*This bug requires specialized knowledge and access to Mozilla's internal systems, so is not a good issue for contributors*

The Glean Dictionary currently has some etl code which you need to run adhoc to create a bunch of static data assets in https://github.com/mozilla/glean-dictionary/blob/12ff6ac8f603f1245f6c6dcb9e4be9b85e28b135/scripts/build-glean-metadata.py -- we may eventually move to storing this in an elastic search cluster (see discussion here: https://docs.google.com/document/d/1OkTWA3rsSJ0m5g9GDnxXVUMkJP-xJMQk_bDgDq-Z9xM/edit#heading=h.tn5dtaq0zat6) but this seems like the easiest approach for now. While we're in this phase, we should schedule this etl code to run after a schema deploy and upload it to the bucket we're using with protosaur (#60). Need to talk to someone from dataops when we're ready to do this.

**Comment by wlach** [comment]
Putting this in the backlog for now, we certainly need to do this but I'm not sure if it's super high priority given our current cadence of deploys to priority.

**Comment by acmiyaguchi** [comment]
This should be higher up now that #374 is going to be a thing. The easiest solution would probably be to add a nightly job via [CircleCI workflows](https://circleci.com/docs/2.0/workflows/#scheduling-a-workflow) that runs around 3-4 AM UTC (to account for probe scraper and mps generation).
