### ISSUE TITLE
Need to deduplicate metrics

### ISSUE THREAD

**Issue by wlach** [mozilla/glean-dictionary#627]
Sometimes libraries have overlapping metrics if you look into the past. For example, `app_build` is present in `glean-core` and *was* present in `glean-android`). This can result in some confusing behaviour in the metric page because we wind up counting the metric twice for each variant:

![image](https://user-images.githubusercontent.com/20569/120046367-fc832f00-bfdf-11eb-8da8-7a7d54606e85.png)

The fix is to add some logic here to only take the latest version of a metric if we notice it occuring more than once when adding the dependency metrics:

https://github.com/mozilla/glean-dictionary/blob/d33ed7a8bfe67bcbf7be6338cc51615493e60dd8/scripts/glean.py#L205

**Comment by wlach** [comment]
@Iinh any interest in taking this on? I think it'd be a good task from the p.o.v. of understanding our metadata pipeline more deeply.

**Comment by Iinh** [comment]
Yes I can work on this! Thanks for filing this issue @wlach
