### ISSUE TITLE
Explain what the commentary is a little better

### ISSUE THREAD

**Issue by wlach** [mozilla/glean-dictionary#640]
The commentary section isn't really well documented, which prompted at least one question internally on "what is this thing":

![image](https://user-images.githubusercontent.com/20569/120488452-c8fc2800-c384-11eb-9bba-ceee30fd66a0.png)

We should make it more clear what it is. Maybe add some help bubbles and expand on the text inside it to make it clear.

**Comment by mcomella** [comment]
(repost from Slack) I feel like the Commentary section should be just below the description – if I was analyzing a probe, I might read the description, see the metadata table, "Ah, I don't need to see any of that for this probe!", and never bother scrolling down to the "Commentary". If the commentary was closer to the top though, I'd be more likely to see and read it.

**Comment by wlach** [comment]
Working on this.

**Comment by wlach** [comment]
> (repost from Slack) I feel like the Commentary section should be just below the description – if I was analyzing a probe, I might read the description, see the metadata table, "Ah, I don't need to see any of that for this probe!", and never bother scrolling down to the "Commentary". If the commentary was closer to the top though, I'd be more likely to see and read it.

I tried this and it looks a little weird to me. I have some help-related improvements inbound but I think the fundamental solution is probably to hide / de-emphasize less useful metadata a little bit, which will require a bit more thought. May wind up filing a new issue for that.
