### ISSUE TITLE
Add ability to search by metric type or description

### ISSUE THREAD

**Issue by fbertsch** [mozilla/glean-dictionary#641]
It's not clear to me how the UX should behave here; e.g. should searching by default be across types and descriptions, or should it be more like a [logs explorer](https://console.cloud.google.com/logs/query;cursorTimestamp=2021-06-02T13:48:19.209941Z?project=moz-fx-data-ingesti-prod-579d) which requires you to select which field you're searching on.

The use case here is to e.g. see which events are available (this makes the Funnel Analysis explore in Looker easier to use). I'd imagine there might be other use cases (e.g. do we already have a counter for some event?).

**Comment by wlach** [comment]
Yup, making search work across types and descriptions would be relatively easy although not extremely discoverable. 

I definitely don't think we want something as complex as the logs explorer example you gave here, but we should probably iterate towards something a little more sophisticated than just a text field that people can type things into. I'll give this a bit more thought in the coming weeks.

**Comment by wlach** [comment]
I'm concerned about the performance impact of doing a fulltext search on the descriptions given how our current searching functionality is written ([very naively and inefficiently](https://github.com/mozilla/glean-dictionary/blob/f0d48f7c6e336a75036bfa3b6a25f903ebabb4a3/src/state/filter.js)). It might be worth adding this type of functionality for types and then figuring out how to add support for descriptions later in a way that doesn't compromise usability (e.g. by using an indexing library like lunr.js)
