### ISSUE TITLE
`Applicant Variant` Fixups

### ISSUE THREAD

**Issue by fbertsch** [mozilla/glean-dictionary#645]
I have two proposals here:
1. Hide all deprecate channels. I don't see any good reason to include them for e.g. Fenix
2. Order with release first, and default to selecting release. Most people's questions will _probably_ be on release data

**Comment by fbertsch** [comment]
Also: Looker uses release as the [default selection](https://github.com/mozilla/lookml-generator/blob/main/generator/views/ping_view.py#L88).

**Comment by wlach** [comment]
> I have two proposals here:
> 
>     1. Hide all deprecate channels. I don't see any good reason to include them for e.g. Fenix

I think we should probably keep them for comprehensiveness, but I can exclude the links to Looker and GLAM and make it more clear they're deprecated.

>     2. Order with release first, and default to selecting release. Most people's questions will _probably_ be on release data

👍
