### ISSUE TITLE
Show event extra's types

### ISSUE THREAD

**Issue by badboy** [mozilla/glean-dictionary#647]
Meta bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1695164

Events can now have an explicit type for extra values, see https://mozilla.github.io/glean/book/reference/metrics/event.html#extra_keys
(This is for the code only, the data will be stringified as it is today)
The dictionary can probably expose this information.

**Comment by wlach** [comment]
@badboy Do you have any examples of this being used yet? It will be easier to validate our visualization of the data if we have that

**Comment by badboy** [comment]
I migrated only one user (and it didn't land yet): https://github.com/mozilla-mobile/android-components/pull/10421/files#diff-f931f692b73dced5e27d9350c4ce967de7eaddb3ddceec603c3812d5605421fdR921-R927

**Comment by wlach** [comment]
@Iinh any interest in tackling this one when you have an extra cycle or two? The required information should be slurped up by our ingestion script, all that needs to be done is updating the metric view to add the new keys.

**Comment by Iinh** [comment]
Sounds like a straightforward task. I'm on it.
