### ISSUE TITLE
Can be hard to tell offhand what product a metric or ping pertains to

### ISSUE THREAD

**Issue by SuYoungHong** [mozilla/glean-dictionary#659]
Had one piece of feedback - it’s really hard, in general, to keep track of what probes exist for iOS vs Fenix glean… and using the glean dictionary for each, i had to keep looking up to the top banner to keep track of which product i was in, for a page (apps/fenix/etc.)
this was really time, and attention intensive.

it would be really great to encode which product we’re in (for like a probe, or search page) visually in some way that’s automatic and unconscious, so users can know what product they’re in almost instantly.

Some suggestions:
* have different background colors for Fenix vs iOS pages (so which product we’re in is color encoded in the background)
* have a giant logo in the white space of the product (not sure if this will work though, since the logo is the same…)

not sure how hard it is to implement… I’m a big fan of the first idea (background color encoding)

**Comment by wlach** [comment]
Thanks for reporting @SuYoungHong! Color coding is a bit of a can of worms in terms of UX design, but it's something we could consider. Some simpler mitigations might be:

1. Keep the header sticky so at least it's always in view:

![image](https://user-images.githubusercontent.com/20569/121083649-b2ebce80-c7ad-11eb-916f-ba398caa99d4.png)

2. Put an Android/Apple/whatever icon beside the app name in the breadcrumbs (just like we do on the app page)

I'd be tempted to start with (1) and go from there.

**Comment by wlach** [comment]
@Iinh I am curious if you have any ideas on the above ^^ (beyond what I suggested)

**Comment by Iinh** [comment]
I agree that color coding can get tricky as it could become visually noisy (we already have a lot of color actions going on). Since it's already sticky, we could color code the bread crumb bar but I think placing the platform logo at the end (2) can achieve the same effect, and might actually look better. I'll start working on (2) and see how it looks first.
