### ISSUE TITLE
Glean dictionary should store page state in URL

### ISSUE THREAD

**Issue by fbertsch** [mozilla/glean-dictionary#693]
Sometimes I'm investigating a metric and would like to share the URL to the glean dictionary page. For example, working with the sync team, they wanted to look at [this metric](https://dictionary.telemetry.mozilla.org/apps/fenix/metrics/creditcards_sync_failure_reason).

The problem is that I wanted to link them to the pre-release "version" of that metric (for nightly), but I can't. I can only link them to the page and tell them to switch to nightly so they can actually see the data in Looker and GLAM.

**Comment by wlach** [comment]
@Iinh can you take this one?
