### ISSUE TITLE
Fails to load page for ios `app_opened_as_default_browser` metric

### ISSUE THREAD

**Issue by ecsmyth** [mozilla/glean-dictionary#695]
# STR
Navigate to the [app_opened_as_default_browser metric page](https://dictionary.telemetry.mozilla.org/apps/firefox_ios/metrics/app_opened_as_default_browser)

or 

Navigate to the [Firefox for iOS page](https://dictionary.telemetry.mozilla.org/apps/firefox_ios/?itemType=metrics&page=1&showExpired=1) and click on the link to app_opened_as_default_browser.

# Expected
Metric page loads and displays relevant information similar to what is available for the [app_build] (https://dictionary.telemetry.mozilla.org/apps/firefox_ios/metrics/app_build) metric.

# Observed
Content in the `main` tag doesn't load. Console reports the error `Uncaught (in promise) TypeError: e[8].tags is null`

**Comment by wlach** [comment]
That's embarassing. I'll do up a hotfix, will think about how to prevent this from happening again
