### ISSUE TITLE
Add a footer to each page

### ISSUE THREAD

**Issue by wlach** [mozilla/glean-dictionary#76]
*This issue is intended as an onboarding task for potential outreachy applicants. Please do not work on it unless you have completed the initial qualification task and it has been assigned to you.*

[GLAM](https://github.com/mozilla/glam) has a footer element with some useful information at the bottom of each page:

![image](https://user-images.githubusercontent.com/20569/95586546-d556fd80-0a0e-11eb-951d-8fe50c3879c3.png)

We should have something similar for the Glean dictionary.

You can mostly copy over the existing footer from GLAM (putting it into the `src/components/` directory) and then put it into each of the pages we display:

https://github.com/mozilla/glam/blob/77c4689297e3c81f6cf49f9fd6f73a9435d1761b/src/components/regions/Footer.svelte

Some styling should be adjusted and obviously the links should be different (e.g. the link to a slack channel should instead be a link to our channel on Matrix: https://chat.mozilla.org/#/room/#glean-dictionary:mozilla.org)

**Comment by wlach** [comment]
Going to assign this to @mridubhatnagar

**Comment by dharmelolar** [comment]
hello, @wlach please can I work on this?

**Comment by wlach** [comment]
We really need this sooner than later, so I'm going to take this over using @mridubhatnagar's excellent initial work as a base.
