### ISSUE TITLE
Add breadcrumbs to help users understand their place in the application

### ISSUE THREAD

**Issue by DawoodShahat** [mozilla/glean-dictionary#83]
After navigating to this page I have no information on where I am on the application.

![ping_page](https://user-images.githubusercontent.com/19612755/95621457-273d6900-0a8b-11eb-8bbe-dede02f4b0c0.png)

Why not add a breadcrumb to help us navigate through the app in a proper way. 

something like this 

App / Fenix / Pings / Activation.

**Comment by DawoodShahat** [comment]
@wlach What do you think about this?

**Comment by UdokaVrede** [comment]
yeah this would be very helpful, I kept turn around for awhile too.

**Comment by wlach** [comment]
This is a great suggestion. I think we should make it a svelte component and use a bit of tailwind to style it (doesn't have to be fancy at this point -- but you can see some examples here: https://tailwind-starter-kit.now.sh/docs/breadcrumbs). As with the footer, I *think* it should be possible to just include this component in the App.svelte and pass the required data to render it correctly based on the currently selected page.

While we're here, I'd also like to see a story for the component (see the section I just added to the README: https://github.com/mozilla/glean-dictionary#storybook). You can model it off of the existing story for the schema viewer:

https://github.com/mozilla/glean-dictionary/blob/main/stories/schemaviewer.stories.js

Note that the stories will look a little weird until #74 is fixed (which will hopefully be soon). As long as the content looks right I'm happy.

**Comment by DawoodShahat** [comment]
Alright, Working on it. Thanks.
