### ISSUE TITLE
Add a tags summary page

### ISSUE THREAD

**Issue by wlach** [mozilla/glean-dictionary#832]
We have a half-finished "tags" page in the source code, which lists out the tags for an application and the number of metrics matching them. This would likely be useful for finding Firefox for Android telemetry. Let's try to finish this up and get some feedback from people on how they like it.

**Comment by Iinh** [comment]
What are some things you have in mind for the Tags/Feature page? Should we work on a separate component, e.g. a FeatureDetail page for each tag?

**Comment by wlach** [comment]
> What are some things you have in mind for the Tags/Feature page? Should we work on a separate component, e.g. a FeatureDetail page for each tag?

That might be something to consider, but I suspect we should just start with a list of the tags. Clicking on the tag should take you to the metrics with that filled in as the search. I think this is 99% ready already, just commented out:

https://github.com/mozilla/glean-dictionary/blob/07acd6113df312b40fe351d338528b88e577733b/src/pages/AppDetail.svelte#L80

Definitely welcome any thoughts you might have though, I could be wrong.
