### ISSUE TITLE
Add some metadata to tell if a metric was recently added

### ISSUE THREAD

**Issue by wlach** [mozilla/glean-dictionary#836]
During the fenix event explore demo yesterday, the question came up on whether it was possible to see when a metric was first added. It currently *isn't* but we the probe info service does provide this information if you look at the revision information.

We should add a metadata column to the table saying when it was first seen and maybe also provide some warning text under "Access" saying that it was recently added.

If an app has more than one channel:

"This metric was recently added. It may take some time before it is available on all channels."

If an app has only one channel (e.g. mozilla vpn):

"This metric was recently added. Data may not be available until a new version is released with this metric and clients are updated to it."

(or something like the above, we can wordsmith in the PR)

**Comment by Iinh** [comment]
Hey @wlach, I can take this issue. 

> the probe info service does provide this information if you look at the revision information.

Before I begin, am I correct in my understanding that this from the example below is where we get the first-added information?

![CleanShot 2021-09-16 at 13 39 06@2x](https://user-images.githubusercontent.com/28797553/133682650-e923bed0-6ea5-41a2-a1f2-dfc66be44a8f.png)

**Comment by wlach** [comment]
Yup that's the right place!
