### ISSUE TITLE
Pagination with Next Previous buttons

### ISSUE THREAD

**Issue by meghajain-1711** [mozilla/glean-dictionary#88]
For pages like http://localhost:5000/#!/apps/fenix , navigation becomes too difficult if the data is too much. 

Apart from filtering as mentioned in another issue, we can also add Next Previous Buttons to show 1 to 100 or page limit. 

This will be useful when user does not have the exact search term to filter.

**Comment by LilyLME** [comment]
Hello @wlach @meghajain-1711 can I work on this?

**Comment by wlach** [comment]
> Hello @wlach @meghajain-1711 can I work on this?

Yup! We're trying to get applicants to do at least one frontend bug as part of their work and this is a good candidate. Thank you @meghajain-1711 for filing.

Pagination that looks something like this would be good:

![image](https://user-images.githubusercontent.com/20569/96122116-05931600-0ebf-11eb-81ea-17a2039c771d.png)

Some inspiration for creating pagination components can be found here:

https://tailwindcomponents.com/component/pagination-example

As part of this issue, I would like to see a story added for this component, you can see an example of that here:

https://github.com/mozilla/glean-dictionary/blob/main/stories/schemaviewer.stories.js

**Comment by Iinh** [comment]
@wlach I think we can close this issue now?

**Comment by wlach** [comment]
> @wlach I think we can close this issue now?

Yup! Thank you @LilyLME and @Iinh for your work here.
