### ISSUE TITLE
Failed to fetch some metrics data for fenix apps.

### ISSUE THREAD

**Issue by DawoodShahat** [mozilla/glean-dictionary#89]
#### Issue description

Failed to fetch some metrics data for fenix apps.
The issue arises only when the metric name starts with metrics.any_metric

#### Steps to reproduce the issue

1.  navigate to [http://localhost:5000/#!/apps/fenix](http://localhost:5000/#!/apps/fenix)
2. search for a metric that starts with metrics.default_browser. Use this link [http://localhost:5000/#!/apps/fenix/metrics/metrics.default_browser](http://localhost:5000/#!/apps/fenix/metrics/metrics.default_browser)

3. Check the browser's console, and It throws this error
 Uncaught (in promise) TypeError: Failed to fetch

4. The issue arises only when the metric name starts with **metrics.any_metric**

#### What's the expected result?

- It should show details about the metrics by rendering MetricDetail.svelte component.

#### What's the actual result?

- It shows a blank screen. 
- An error on the browser's console.

####  Screenshots

- ![Screenshot 2020-10-12 at 12 07 45 AM](https://user-images.githubusercontent.com/19612755/95687742-fbeb8300-0c1e-11eb-99a1-af8e3aadde5a.png)

-

**Comment by meghajain-1711** [comment]
Hi @DawoodShahat 
I am not able to reproduce this issue, 
I can clearly see the information as required.

This is with metric Detail added by my latest PR
![image](https://user-images.githubusercontent.com/59704142/95687917-33106300-0c24-11eb-8be0-7757d22daa14.png)

But even without my PR I can see the page as expected
![image](https://user-images.githubusercontent.com/59704142/95687992-95696380-0c24-11eb-9a9c-029876e4fd2c.png)

**Comment by DawoodShahat** [comment]
Thank you, I tried this on different browsers and it seems to work on firefox. But on google chrome, It still doesn't work. I think the local JSON request might be blocked by some extensions.

**Comment by meghajain-1711** [comment]
https://stackoverflow.com/questions/49343024/getting-typeerror-failed-to-fetch-when-the-request-hasnt-actually-failed/49895164

This one suggests just adding http before :) 
Glad , I could help !

**Comment by DawoodShahat** [comment]
I tried that one before. it didn't work out well. Someone suggested to disable extensions and by doing so it resolved the issue.

**Comment by edward-hong** [comment]
Hi I can confirm that it works on Firefox but not on Chrome due to extensions also

**Comment by DawoodShahat** [comment]
Hey, In my case It didn't work because of ad blocker extension.
