### ISSUE TITLE
Show expiry information for Firefox

### ISSUE THREAD

**Issue by wlach** [mozilla/glean-dictionary#984]
Firefox desktop uses version numbers instead of dates for expiry. For example:

https://dictionary.telemetry.mozilla.org/apps/firefox_desktop/metrics/browser_engagement_uri_count

@badboy and I discussed this a bit on #glean-dictionary:

@wlach:

> It looks like Firefox metrics have a different notion of expiry (by "release") than that of other applications e.g. https://dictionary.telemetry.mozilla.org/apps/firefox_desktop/metrics/browser_link_open_newwindow_restriction
> 
> How should the Glean Dictionary handle these? The simplest solution I can think of would be to use the product details API to map releases to dates (as we can): https://product-details.mozilla.org/1.0/firefox.json

@badboy:

> Yes. build date is not good for firefox, glean_parser allows to change how expiry is defined and in fog we use the firefox version, just as legacy telemetry does (also ensures that tooling keeps working, in both directions of history, that is you can build old firefox without expiring metrics and you can test newer versions and see which ones expire)

> I like the idea of mapping it to actual releases.
> It has some problems though:
> - metrics exist in nightly, so there they will expire ~8 weeks before they do in release (because that's the time it takes for the versions to rollover). product details has only release details
> - product details has releases for the past, not the future.

--

Tentative proposal:

* In our python scripts, get a list of release dates from the above mentioned product details API (https://product-details.mozilla.org/1.0/firefox.json)
* Add an `expiry_date` field to the outputted JSON which is guaranteed to be a date. For most applications, this will just be the `expires` field. For Firefox, we will use the mapping above.
* Replace "expires" with a markdown string that we can render in the Glean Dictionary. For most applications, keep this the same (since they're just dates), but for Firefox we can replace it with something like: `100 (latest release is [94](https://wiki.mozilla.org/Release_Management/Calendar))`. Hopefully that will be enough information for people to reason about nightly and beta releases as well.

Thoughts?

**Comment by wlach** [comment]
Example of what this would look like:

![image](https://user-images.githubusercontent.com/20569/143886441-8f2564df-51ea-437e-bb2a-b97ff89c77ac.png)

**Comment by chutten** [comment]
Which date are you choosing for `expiry_date`? The product details API you linked only includes release and beta. But a metric will be expired in Nightly before that time.

**Comment by wlach** [comment]
> Which date are you choosing for `expiry_date`? The product details API you linked only includes release and beta. But a metric will be expired in Nightly before that time.

Oops, forgot to mention that. I would suggest using the release date (yes, the fact that things will expire in beta and nightly sooner is a bit of a gotcha-- suggestions on what to do about that welcome)

**Comment by chutten** [comment]
Without switching from product details to buildhub2 to get nightly dates, release is the best one to aim for. (in which case the simpler [history of major releases file](https://product-details.mozilla.org/1.0/firefox_history_major_releases.json) could be used instead)

To know whether this is an acceptable gotcha rather depends on the use cases you see for the `expiry_date` field. Since it'll be a new one, did you have a user in mind already?

In other news:  I love the markdown display. But it gets a little sticky where you put that very helpful "latest release is X". Because the information you're relating here in the dictionary is the latest information from Nightly. The markdown readout suggests that this metric is being recorded now in the latest release of 94... when really it might be only landed in Nightly 96.

Since Glean Dictionary seems to be (wisely) avoiding reflecting the full expiry history the way Probe Dictionary did, we might not be interested in including too much confusing information here. A little note inside the `i` saying that this expiry information reflects the latest information present in Nightly builds might be enough (though we will have to drop the "latest release is X" line... which I don't wanna, because that'd be so darn helpful)

Gosh, why does it have to be so darn complicated.

**Comment by wlach** [comment]
> Without switching from product details to buildhub2 to get nightly dates, release is the best one to aim for. (in which case the simpler [history of major releases file](https://product-details.mozilla.org/1.0/firefox_history_major_releases.json) could be used instead)

TIL!

> To know whether this is an acceptable gotcha rather depends on the use cases you see for the `expiry_date` field. Since it'll be a new one, did you have a user in mind already?

Oh, the usual suspects (in rough order of importance):

1. Data Scientists
2. Product Managers
3. Engineering (both Data and Product)

I expect that experienced users of all descriptions will understand the release train model, but providing some hints might be helpful for onboarding.

> In other news: I love the markdown display. But it gets a little sticky where you put that very helpful "latest release is X". Because the information you're relating here in the dictionary is the latest information from Nightly. The markdown readout suggests that this metric is being recorded now in the latest release of 94... when really it might be only landed in Nightly 96.

We have a "recently added" warning which I think might help in this case?

![image](https://user-images.githubusercontent.com/20569/143903749-183525f3-d124-4662-b56c-8e432fbd0b64.png)

> Since Glean Dictionary seems to be (wisely) avoiding reflecting the full expiry history the way Probe Dictionary did, we might not be interested in including too much confusing information here. A little note inside the `i` saying that this expiry information reflects the latest information present in Nightly builds might be enough (though we will have to drop the "latest release is X" line... which I don't wanna, because that'd be so darn helpful)

It's a bit of a tradeoff between a certain amount of ambiguity and providing the right context for experienced users. I'd personally vote to favor the latter: hopefully the link to the rapid release calendar will be helpful to the confused.

**Comment by chutten** [comment]
Maybe we link to the Release Calendar plainly, then, without parsing for the current train (see also https://whattrainisitnow.com/). 

But no other app gets special train treatment (though they split their app ids, but then you combine them to a single family for display...), so maybe I'm overthinking and we can put it in and iterate as we learn how folks use it.

> We have a "recently added" warning which I think might help in this case?

I dunno. For whatever reason I parse that warning as to do with schema deploys and uptake curves, not trains. Though if we wanted to warn about trains, that'd be good decent place for it (for apps that have trains).

Consider my objections addressed upon reflection. Glean Dictionary is very mutable, so theorizing about potential trip hazards is less valuable than putting something up and seeing how folks use it.

**Comment by Iinh** [comment]
Sure, I can start working on this!
